# Generated by Django 4.2.30 on 2026-09-28 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_done', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='assignments.assignment')),
            ],
            options={
                'db_table': 'subtask',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PersonalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='assignments.assignment')),
            ],
            options={
                'db_table': 'personal_note',
            },
        ),
        migrations.CreateModel(
            name='DeadlineHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_due', models.DateTimeField(blank=True, null=True)),
                ('new_due', models.DateTimeField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='GRAPH', max_length=10)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_history', to='assignments.assignment')),
            ],
            options={
                'db_table': 'deadline_history',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('url_or_drive_id', models.TextField()),
                ('kind', models.CharField(choices=[('SPEC', 'Specification'), ('TEMPLATE', 'Template'), ('RUBRIC', 'Rubric'), ('LINK', 'Link')], default='LINK', max_length=20)),
                ('added_by', models.CharField(choices=[('TEAMS', 'Microsoft Teams'), ('USER', 'User')], default='USER', max_length=10)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assignments.assignment')),
            ],
            options={
                'db_table': 'attachment',
            },
        ),
        migrations.CreateModel(
            name='AiSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('requirements', models.JSONField(blank=True, null=True)),
                ('deadlines', models.JSONField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summary', to='assignments.assignment')),
            ],
            options={
                'db_table': 'ai_summary',
            },
        ),
        migrations.CreateModel(
            name='AiFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('UP', 'Helpful'), ('DOWN', 'Not helpful')], max_length=10)),
                ('corrected_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='ai_assistant.aisummary')),
            ],
            options={
                'db_table': 'ai_feedback',
            },
        ),
    ]
