# Generated by Django 4.2.30 on 2026-09-28 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrosoftAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teams_user_id', models.CharField(max_length=64, unique=True)),
                ('tenant_id', models.CharField(max_length=64)),
                ('scopes_granted', models.TextField()),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='microsoft_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'microsoft_account',
            },
        ),
    ]
